eureka:
  client:
    serviceUrl:
      defaultZone: "http://eureka:password@localhost:8761/eureka"

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: thinguyen01683@gmail.com
    password: qcintvqlwpgdwzdo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:com.example.BookingNotification
server:
  port: 8087