
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/room
    username: postgres
    password: 123456
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    locations: classpath:db/migration
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost
jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
server:
  port: 8083
